"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowRight, Brain, Check, Loader2, Pencil, Power, PowerOff, ShieldCheck, Sparkles, Trash2, X } from "lucide-react";
import { CreatorIndustryDNA } from "./CreatorIndustryDNA";

type Signal = { id: string; field_path: string; before_value: unknown; after_value: unknown; is_active: boolean; confirmed_at: string | null; created_at: string };
type Rule = { id: string; category: string; scope: string; rule_text: string; evidence_count: number; status: "suggested" | "confirmed"; is_active: boolean; confirmed_at: string | null };

export function EggPreferencesClient() {
  const [signals, setSignals] = useState<Signal[]>([]);
  const [rules, setRules] = useState<Rule[]>([]);
  const [loading, setLoading] = useState(true);
  const [busyId, setBusyId] = useState("");
  const [filter, setFilter] = useState("全部");
  const [error, setError] = useState("");
  const [suggesting, setSuggesting] = useState(false);
  const [editingRule, setEditingRule] = useState("");
  const [ruleDraft, setRuleDraft] = useState("");
  useEffect(() => { void loadSignals(); }, []);
  async function loadSignals() { setLoading(true); setError(""); try { const response = await fetch("/api/egg/preferences"); const result = await response.json(); if (!response.ok) throw new Error(result.error); setSignals(result.signals ?? []); setRules(result.rules ?? []); } catch (cause) { setError(cause instanceof Error ? cause.message : "暫時未能載入 Creator DNA"); } finally { setLoading(false); } }
  async function suggestRules() { setSuggesting(true); setError(""); try { const response = await fetch("/api/egg/dna-rules/suggest", { method: "POST" }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setRules((current) => [...current.filter((rule) => rule.status === "confirmed"), ...(result.rules ?? [])]); } catch (cause) { setError(cause instanceof Error ? cause.message : "未能整理 DNA 建議"); } finally { setSuggesting(false); } }
  async function updateRule(rule: Rule, body: { ruleText?: string; isActive?: boolean; confirmed?: boolean; scope?: string }) { setBusyId(rule.id); setError(""); try { const response = await fetch(`/api/egg/dna-rules/${rule.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setRules((current) => current.map((item) => item.id === rule.id ? result.rule : item)); setEditingRule(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "未能更新 DNA 規則"); } finally { setBusyId(""); } }
  const categories = useMemo(() => ["全部", ...new Set(signals.map((signal) => categoryFor(signal.field_path)))], [signals]);
  const visible = filter === "全部" ? signals : signals.filter((signal) => categoryFor(signal.field_path) === filter);
  async function updateSignal(signal: Signal, body: { isActive?: boolean; confirmed?: boolean }) { setBusyId(signal.id); setError(""); try { const response = await fetch(`/api/egg/preferences/${signal.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setSignals((current) => current.map((item) => item.id === signal.id ? { ...item, ...result.signal } : item)); } catch (cause) { setError(cause instanceof Error ? cause.message : "未能更新 Creator DNA"); } finally { setBusyId(""); } }
  async function deleteSignal(signal: Signal) { if (!window.confirm("確定永久刪除這項 Creator DNA 紀錄？刪除後不能復原。")) return; setBusyId(signal.id); try { const response = await fetch(`/api/egg/preferences/${signal.id}`, { method: "DELETE" }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setSignals((current) => current.filter((item) => item.id !== signal.id)); } catch (cause) { setError(cause instanceof Error ? cause.message : "未能刪除 Creator DNA 紀錄"); } finally { setBusyId(""); } }
  const activeCount = signals.filter((signal) => signal.is_active).length;
  const confirmedRules = rules.filter((rule) => rule.status === "confirmed" && rule.is_active);
  const confirmedCount = confirmedRules.length;
  const learningCategoryCount = new Set(signals.filter((signal) => signal.is_active).map((signal) => categoryFor(signal.field_path))).size;
  return <main className="min-h-screen bg-[#f7f7f8] px-4 pb-12 pt-[8vh] sm:px-6"><div className="mx-auto max-w-5xl">
    <header><p className="text-xs font-bold uppercase tracking-[0.2em] text-amber-700">你的內容風格</p><h1 className="mt-2 text-3xl font-black text-zinc-950">Creator DNA</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-zinc-500">每次你儲存內容修改，EGG 都會記下前後差異。你可以停用不準確的紀錄，並確認真正代表你的創作規則。</p></header>
    <CreatorIndustryDNA />
    <section className="mt-6 grid gap-3 sm:grid-cols-3"><Stat label="修改紀錄" value={signals.length} /><Stat label="正在參考" value={activeCount} /><Stat label="已確認規則" value={confirmedCount} /></section>
    <section className="mt-6 overflow-hidden rounded-3xl bg-[#241d1b] p-5 text-white sm:p-6">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <p className="text-xs font-bold uppercase tracking-[0.18em] text-[#f4bf47]">目前生效</p>
          <h2 className="mt-1 text-xl font-black">EGG 對你的理解</h2>
          <p className="mt-1 text-xs leading-5 text-zinc-400">只有你確認並保持啟用的規則，才會在生成內容時優先使用。</p>
        </div>
        <span className="rounded-full border border-white/15 bg-white/10 px-3 py-1.5 text-xs font-bold text-zinc-200">{confirmedCount} 項已確認</span>
      </div>
      {confirmedRules.length ? <div className="mt-5 grid gap-3 sm:grid-cols-2">{confirmedRules.map((rule) => <article key={rule.id} className="rounded-2xl border border-white/10 bg-white/[0.07] p-4">
        <div className="flex items-center justify-between gap-3"><span className="text-xs font-black text-[#f4bf47]">{rule.category}</span><span className="text-[11px] text-zinc-400">{scopeLabel(rule.scope)}</span></div>
        <p className="mt-2 text-sm font-semibold leading-6 text-white">{rule.rule_text}</p>
        <p className="mt-3 text-[11px] text-zinc-400">根據 {rule.evidence_count} 次內容修改歸納</p>
      </article>)}</div> : <div className="mt-5 rounded-2xl border border-dashed border-white/20 bg-white/[0.05] p-5">
        <p className="text-sm font-bold">EGG 仍在了解你的創作習慣</p>
        <p className="mt-1 text-xs leading-5 text-zinc-400">目前有 {activeCount} 項有效修改，涵蓋 {learningCategoryCount} 個方向。分析修改並確認規則後，這裡便會顯示你的 Creator DNA。</p>
      </div>}
      <div className="mt-5 flex flex-wrap items-center gap-2 text-[11px] font-bold text-zinc-300"><span className="rounded-full bg-white/10 px-3 py-2">1　儲存修改</span><ArrowRight className="h-3.5 w-3.5 text-zinc-500" /><span className="rounded-full bg-white/10 px-3 py-2">2　EGG 歸納規則</span><ArrowRight className="h-3.5 w-3.5 text-zinc-500" /><span className="rounded-full bg-white/10 px-3 py-2">3　你確認後使用</span></div>
    </section>
    <section className="mt-6 rounded-3xl border border-amber-200 bg-amber-50 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><Sparkles className="h-4 w-4 text-amber-700" /><h2 className="font-black text-zinc-950">Creator DNA 規則建議</h2></div><p className="mt-1 text-xs leading-5 text-zinc-600">同一類至少有 2 個修改，EGG 才會歸納。只有你確認的規則會優先套用。</p></div><button type="button" onClick={() => void suggestRules()} disabled={suggesting || activeCount < 2} className="inline-flex items-center gap-2 rounded-xl bg-zinc-950 px-4 py-2 text-xs font-bold text-white disabled:opacity-40">{suggesting ? <Loader2 className="h-4 w-4 animate-spin" /> : <Sparkles className="h-4 w-4" />}{suggesting ? "正在分析…" : rules.length ? "重新分析建議" : "分析我的修改"}</button></div>
      {rules.length ? <div className="mt-4 space-y-3">{rules.map((rule) => <article key={rule.id} className="rounded-2xl border border-amber-200 bg-white p-4"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-amber-100 px-2 py-1 text-[11px] font-black text-amber-800">{rule.category}</span><span className="text-xs text-zinc-400">來自 {rule.evidence_count} 個修改</span><select aria-label="適用範圍" value={rule.scope} onChange={(event) => void updateRule(rule, { scope: event.target.value })} className="ml-auto rounded-lg border border-zinc-200 bg-white px-2 py-1 text-xs"><option value="all">所有內容</option><option value="presenter">真人出鏡</option><option value="ai_visual">AI 短片</option><option value="carousel">多圖圖卡</option><option value="single_image">單圖 Post</option><option value="snapshot_reference">拍攝參考圖</option></select></div>{editingRule === rule.id ? <div className="mt-3"><textarea value={ruleDraft} onChange={(event) => setRuleDraft(event.target.value)} rows={3} className="w-full rounded-xl border border-zinc-200 p-3 text-sm leading-6 outline-none focus:border-amber-400" /><div className="mt-2 flex gap-2"><button type="button" onClick={() => void updateRule(rule, { ruleText: ruleDraft })} className="rounded-lg bg-zinc-950 px-3 py-2 text-xs font-bold text-white">儲存規則</button><button type="button" onClick={() => setEditingRule("")} className="rounded-lg border px-3 py-2 text-xs font-bold"><X className="h-3.5 w-3.5" /></button></div></div> : <p className="mt-3 text-sm font-semibold leading-6 text-zinc-900">{rule.rule_text}</p>}<div className="mt-3 flex flex-wrap gap-2"><button type="button" onClick={() => { setEditingRule(rule.id); setRuleDraft(rule.rule_text); }} className="inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-xs font-bold"><Pencil className="h-3.5 w-3.5" />編輯</button><button type="button" onClick={() => void updateRule(rule, { isActive: !rule.is_active })} className="rounded-lg border px-3 py-2 text-xs font-bold">{rule.is_active ? "使用中" : "已停用"}</button><button type="button" disabled={!rule.is_active} onClick={() => void updateRule(rule, { confirmed: rule.status !== "confirmed" })} className={`rounded-lg px-3 py-2 text-xs font-bold ${rule.status === "confirmed" ? "bg-emerald-600 text-white" : "bg-amber-400 text-zinc-950"}`}>{rule.status === "confirmed" ? "已確認 DNA" : "確認並啟用"}</button></div></article>)}</div> : <p className="mt-4 rounded-2xl bg-white/70 p-4 text-xs text-zinc-500">尚未建立規則建議。EGG 不會在證據不足時自行猜測。</p>}
    </section>
    <div className="mt-8"><h2 className="text-lg font-black text-zinc-950">學習紀錄</h2><p className="mt-1 text-xs text-zinc-500">查看 EGG 從哪些實際修改取得 Creator DNA。</p></div>
    <div className="mt-4 flex gap-2 overflow-x-auto pb-1">{categories.map((category) => <button key={category} type="button" onClick={() => setFilter(category)} className={`shrink-0 rounded-full px-4 py-2 text-xs font-bold ${filter === category ? "bg-zinc-950 text-white" : "border border-zinc-200 bg-white text-zinc-600"}`}>{category}</button>)}</div>
    {error ? <p role="alert" className="mt-4 rounded-2xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p> : null}
    {loading ? <div className="mt-8 flex items-center justify-center gap-2 text-sm text-zinc-500"><Loader2 className="h-4 w-4 animate-spin" />正在載入 Creator DNA…</div> : visible.length ? <div className="mt-5 space-y-3">{visible.map((signal) => <article key={signal.id} className={`rounded-3xl border bg-white p-5 shadow-sm ${signal.is_active ? "border-zinc-200" : "border-zinc-200 opacity-60"}`}>
      <div className="flex flex-wrap items-start justify-between gap-3"><div><span className="rounded-full bg-amber-50 px-2.5 py-1 text-[11px] font-black text-amber-800">{categoryFor(signal.field_path)}</span><p className="mt-2 text-xs text-zinc-400">{labelFor(signal.field_path)} · {formatDate(signal.created_at)}</p></div><div className="flex gap-2"><button type="button" disabled={busyId === signal.id} onClick={() => void updateSignal(signal, { isActive: !signal.is_active })} className="inline-flex items-center gap-1 rounded-xl border border-zinc-200 px-3 py-2 text-xs font-bold text-zinc-700">{signal.is_active ? <Power className="h-3.5 w-3.5" /> : <PowerOff className="h-3.5 w-3.5" />}{signal.is_active ? "使用中" : "已停用"}</button><button type="button" disabled={busyId === signal.id} onClick={() => void deleteSignal(signal)} className="rounded-xl border border-zinc-200 p-2 text-zinc-400 hover:text-red-600" aria-label="刪除偏好"><Trash2 className="h-4 w-4" /></button></div></div>
      <div className="mt-4 grid gap-3 md:grid-cols-2"><div className="rounded-2xl bg-zinc-50 p-4"><p className="text-[11px] font-bold text-zinc-400">EGG 原本寫法</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-zinc-600">{displayValue(signal.before_value)}</p></div><div className="rounded-2xl border border-emerald-100 bg-emerald-50 p-4"><p className="text-[11px] font-bold text-emerald-700">你改成</p><p className="mt-2 whitespace-pre-wrap text-sm font-semibold leading-6 text-zinc-900">{displayValue(signal.after_value)}</p></div></div>
      <button type="button" disabled={busyId === signal.id || !signal.is_active} onClick={() => void updateSignal(signal, { confirmed: !signal.confirmed_at })} className={`mt-4 inline-flex items-center gap-2 rounded-xl px-3 py-2 text-xs font-bold ${signal.confirmed_at ? "bg-emerald-600 text-white" : "border border-zinc-200 text-zinc-700"}`}>{signal.confirmed_at ? <Check className="h-4 w-4" /> : <ShieldCheck className="h-4 w-4" />}{signal.confirmed_at ? "已確認為 Creator DNA" : "加入 Creator DNA"}</button>
    </article>)}</div> : <div className="mt-8 rounded-3xl border border-dashed border-zinc-300 bg-white p-10 text-center"><Brain className="mx-auto h-8 w-8 text-zinc-300" /><p className="mt-3 text-sm font-bold text-zinc-700">這個分類暫時未有 Creator DNA 紀錄</p></div>}
  </div></main>;
}

function Stat({ label, value }: { label: string; value: number }) { return <div className="rounded-2xl border border-zinc-200 bg-white p-4"><p className="text-xs text-zinc-500">{label}</p><p className="mt-1 text-2xl font-black text-zinc-950">{value}</p></div>; }
function scopeLabel(scope: string) { return ({ all: "所有內容", presenter: "真人短片", ai_visual: "AI 短片", carousel: "多圖圖卡", single_image: "單圖帖文", snapshot_reference: "拍攝參考" } as Record<string, string>)[scope] ?? "指定內容"; }
function categoryFor(path: string) { if (path === "title") return "標題"; if (path === "hook") return "Hook"; if (path.includes("caption") || path.includes("cta")) return "Caption／CTA"; if (path.includes("host_lines") || path.includes("vo")) return "語氣／台詞"; if (/visual|image|shot|scene|reference|cover|slide/.test(path)) return "視覺方向"; return "其他"; }
function labelFor(path: string) { return path.replace(/\[(\d+)\]/g, " 第 $1 項").replaceAll(".", " › ").replaceAll("_", " "); }
function displayValue(value: unknown) { const text = typeof value === "string" ? value : JSON.stringify(value ?? ""); return text || "（空白）"; }
function formatDate(value: string) { return new Intl.DateTimeFormat("zh-HK", { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" }).format(new Date(value)); }
