create table if not exists public.egg_reply_messages (
  id uuid primary key default gen_random_uuid(),
  creator_id uuid not null references public.egg_creator_profiles(id) on delete cascade,
  role text not null check (role in ('user', 'assistant')),
  content text not null check (char_length(content) between 1 and 12000),
  created_at timestamptz not null default now()
);

create index if not exists egg_reply_messages_creator_created_idx
  on public.egg_reply_messages (creator_id, created_at desc);

create table if not exists public.egg_reply_history_migrations (
  user_id uuid primary key references auth.users(id) on delete cascade,
  creator_id uuid not null references public.egg_creator_profiles(id) on delete cascade,
  migrated_at timestamptz not null default now()
);

create table if not exists public.egg_reply_usage (
  id bigint generated by default as identity primary key,
  creator_id uuid not null references public.egg_creator_profiles(id) on delete cascade,
  created_at timestamptz not null default now()
);

create index if not exists egg_reply_usage_creator_created_idx
  on public.egg_reply_usage (creator_id, created_at desc);

alter table public.egg_reply_messages enable row level security;
alter table public.egg_reply_history_migrations enable row level security;
alter table public.egg_reply_usage enable row level security;

revoke all on public.egg_reply_messages from anon, authenticated;
revoke all on public.egg_reply_history_migrations from anon, authenticated;
revoke all on public.egg_reply_usage from anon, authenticated;
revoke all on sequence public.egg_reply_usage_id_seq from anon, authenticated;

grant all on public.egg_reply_messages to service_role;
grant all on public.egg_reply_history_migrations to service_role;
grant all on public.egg_reply_usage to service_role;
grant all on sequence public.egg_reply_usage_id_seq to service_role;
